### ISSUE TITLE
终端命令行下如何使用代理？

### ISSUE THREAD

**Issue by anlexN** [the0demiurge/ShadowSocksShare-OpenShift#12]
代理已经成功，浏览器也能访问被限制的网站，就是终端不能！我要网上相关资料：set http_proxy=127.0.0.1:1080, 还是无法设置！！！

**Comment by the0demiurge** [comment]
tsocks

在我的网站的“客户端”页面有终端的客户端介绍及其简易教程

**Comment by anlexN** [comment]
windows环境怎么使用？您网站上面只是linux使用啊，@the0demiurge

**Comment by the0demiurge** [comment]
你是说Windows的终端？我不太清楚，ssr客户端设置为全局代理大概就可以了吧

**Comment by anlexN** [comment]
对啊，ssr设为全局，还是在windows命令提示符ping google.com不通。不信，您自己试试。我现在急用啊。请帮忙

**Comment by anlexN** [comment]
![3](https://user-images.githubusercontent.com/8686739/32133417-f387a8fa-bc09-11e7-8d6c-9060bac5b088.png)
有图有真相！

**Comment by the0demiurge** [comment]
https://www.alwayscoder.com/how-to-force-any-software-using-socks-proxy/

在网上找到了个教程，你可以试试看，用这个软件看看能不能选中C:/windows/system32/and.exe
如果不好用的话我也爱莫能助啊😂

**Comment by anlexN** [comment]
不行啊，你自己成功没？@the0demiurge

**Comment by the0demiurge** [comment]
我没有windows，测试不了啊

**Comment by anlexN** [comment]
开虚拟机试一下

**Comment by the0demiurge** [comment]
额，我也没这功夫啊，哈哈
