### ISSUE TITLE
发现一个免费ss网站

### ISSUE THREAD

**Issue by littleguyy** [the0demiurge/ShadowSocksShare-OpenShift#15]
http://shadowsocksph.space/
被墙了，用socks代理能访问。

**Comment by the0demiurge** [comment]
非常感谢，不过有几个原因导致我暂时不会去爬这家的帐号：
1. 这个网站比较新，界面看起来基于WordPress，不知道会不会过几天就跑路了
2. 因为基于wordpress，而且没直接分享ss链接，需要手动编写规则，有点麻烦
3. 目前爬到很多帐号基本都能用，没太多必要去爬他们家的
4. 现在我的主要任务还是看书学习科研。。。

这个网站我记下来了，如果我网站上的ss帐号几乎全都被封禁，我会专门找时间更新一批源的：）

**Comment by lalaxiao1258** [comment]
请问网站上面的订阅地址怎么使用

**Comment by littleguyy** [comment]
https://go.ishadowx.net/

**Comment by the0demiurge** [comment]
那个网站我也爬了，不过爬到的帐号基本全都是失效帐号

**Comment by the0demiurge** [comment]
我刚发现了一个免费分享ss账号网站的合辑，可以在最下方“不需要注册”的区域找找看有没有能用的账号：）

如果以后免费ss资源枯竭了我大概会从这里找找

http://www.shadowmars.tk/shadowsock-site

**Comment by littleguyy** [comment]
https://global.ishadowx.net/img/qr/usaxxoo.png
https://global.ishadowx.net/img/qr/usbxxoo.png
https://global.ishadowx.net/img/qr/uscxxoo.png
https://global.ishadowx.net/img/qr/jpaxxoo.png
https://global.ishadowx.net/img/qr/jpbxxoo.png
https://global.ishadowx.net/img/qr/jpcxxoo.png
https://global.ishadowx.net/img/qr/sgaxxoo.png
https://global.ishadowx.net/img/qr/sgbxxoo.png
https://global.ishadowx.net/img/qr/sgcxxoo.png
不知道，这些可不可以。

**Comment by vicyxy** [comment]
52ssr.cn 这个站

**Comment by vicyxy** [comment]
https://52ssr.cn
