### ISSUE TITLE
订阅有很多重复地址

### ISSUE THREAD

**Issue by chaohua27** [the0demiurge/ShadowSocksShare-OpenShift#16]
目前发现逗比根据地的几乎都有重复地址，因为将他的镜像站的也抓过来了。建议不抓取镜像站，或者有IP加端口去重机制。

**Comment by the0demiurge** [comment]
多谢反馈，我过些时间加入个去重功能：）

**Comment by jzmswe** [comment]
首先感谢作者，辛苦了，非常感谢！再小小地摧一下，24天了，订阅后还是有很多重复地址。

**Comment by the0demiurge** [comment]
最近时间不多，而且这个需求我个人感觉不是十分紧迫，所以就搁置啦：）

也欢迎喜欢搞编程的朋友们稍微研究一下ss_free.py然后把这个功能实现一下：）

**Comment by the0demiurge** [comment]
不同网站之间的重复问题现在基本不存在，所以没有来做这个功能（也没必要做），因此本 issue 的问题基本已经解决：）
