### ISSUE TITLE
分享连接

### ISSUE THREAD

**Issue by DEMON414** [the0demiurge/ShadowSocksShare-OpenShift#18]
https://yoonalim.cf/#Server

乌克兰节点
IP：86.110.117.125
端口：8080
密码：yoonalim.cf
加密：none
协议：auth_chain_a
混淆：tls1.2_ticket_auth
SSR连接：ssr://ODYuMTEwLjExNy4xMjU6ODA4MDphdXRoX2NoYWluX2E6bm9uZTp0bHMxLjJfdGlja2V0X2F1dGg6ZVc5dmJtRnNhVzB1WTJZLz9vYmZzcGFyYW09JnJlbWFya3M9NUxtTTVZV0w1WVd3Jmdyb3VwPVdXOXZibUZzYVcwdVkyWQ

俄罗斯节点
IP：82.202.252.119
端口：8080
密码：yoonalim.cf
加密：none
协议：auth_chain_a
混淆：tls1.2_ticket_auth
SSR连接：ssr://ODIuMjAyLjI1Mi4xMTk6ODA4MDphdXRoX2NoYWluX2E6bm9uZTp0bHMxLjJfdGlja2V0X2F1dGg6ZVc5dmJtRnNhVzB1WTJZLz9vYmZzcGFyYW09JnJlbWFya3M9NUwtRTU3Mlg1cGF2Jmdyb3VwPVdXOXZibUZzYVcwdVkyWQ

**Comment by the0demiurge** [comment]
十分感谢：）
