### ISSUE TITLE
新版本python3 utf 8 兼容

### ISSUE THREAD

**Issue by zhangsmallchi** [the0demiurge/ShadowSocksShare-OpenShift#19]
应将
`# -*- utf-8 -*-`
更改为
`# -*- coding: utf-8 -*-`

**Comment by the0demiurge** [comment]
`grep -r '# -\*- utf-8 -\*-'|sed 's/:.*$//g'|xargs sed 's/# -\*- utf-8 -\*-/# -*- coding: utf-8 -*-/g' {} -i
`
