### ISSUE TITLE
这个可以部署到google的App Engine上吗

### ISSUE THREAD

**Issue by littleguyy** [the0demiurge/ShadowSocksShare-OpenShift#20]
那上不会进入睡眠。

**Comment by the0demiurge** [comment]
当前还是不能直接部署到gae上面的，当然可以研究一下看看怎么弄，等我考完试会考虑研究研究：）

**Comment by bccorp** [comment]
following...

**Comment by the0demiurge** [comment]
https://github.com/the0demiurge/ShadowSocksShare-OpenShift#pythonanywherecom-%E9%83%A8%E7%BD%B2%E6%96%B9%E6%B3%95

今天抽空写了个部署到pythonanywhere.com的教程，这里也不会进入睡眠；过会看看gae文档

**Comment by the0demiurge** [comment]
gae似乎必须用信用卡注册才能成功部署，详情请看readme
