### ISSUE TITLE
Heroku 部署方法，进行到这一步进行不下去了

### ISSUE THREAD

**Issue by jzmswe** [the0demiurge/ShadowSocksShare-OpenShift#27]
4.在部署 (Deploy) 页面选择 GitHub，在Connect to GitHub 这一栏连接上你的 GitHub 帐号，搜索并连接本项目

提示信息：No repos found for jzmswe/the0demiurge

就是这个“搜索并连接本项目”，搜索不到，进行不下去了。

还有
2.Fork 本项目

是什么意思？应该怎样操作？

**Comment by the0demiurge** [comment]
![image](https://user-images.githubusercontent.com/11363529/34807062-808e79d0-f6c1-11e7-9443-7849be03dd33.png)
点击这个按钮就可以fork本项目
然后在这里搜索Shadow
![image](https://user-images.githubusercontent.com/11363529/34807385-832834fe-f6c3-11e7-91f0-6d2e0b8969df.png)
选中就可以了

**Comment by the0demiurge** [comment]
你需要搜索的是“ShadowSocksShare-OpenShift”,是不带"the0demiurge/"的，才能搜到
