### ISSUE TITLE
你好，一个报错

### ISSUE THREAD

**Issue by StefanZeng** [the0demiurge/ShadowSocksShare-OpenShift#3]
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    from app import app
  File "/root/tools/ShadowSocksShare-OpenShift/app/__init__.py", line 117
SyntaxError: Non-ASCII character '\xe2' in file /root/tools/ShadowSocksShare-OpenShift/app/__init__.py on line 117, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

不知道哪里不合适？

**Comment by the0demiurge** [comment]
non-ascii错误很可能是由python版本引起的，你用的是python3吗？

**Comment by the0demiurge** [comment]
merge to #5
