### ISSUE TITLE
每次进入都是“别着急，正在爬数据，十分钟后再回来吧”

### ISSUE THREAD

**Issue by thosethings** [the0demiurge/ShadowSocksShare-OpenShift#34]
看了一下源码，没怎么看明白......有时间再继续琢磨。
作者有时间解决一下这个问题吗？

**Comment by the0demiurge** [comment]
因为正在爬数据和验证数据，而如果访问量太小，heroku会暂时关闭你的实例；更多讨论见
https://github.com/the0demiurge/ShadowSocksShare-OpenShift/issues/17#issuecomment-350981367
