### ISSUE TITLE
请教~！~

### ISSUE THREAD

**Issue by SmallGaoX** [the0demiurge/ShadowSocksShare-OpenShift#35]
请问能教教怎么本地部署吗？谢谢

**Comment by the0demiurge** [comment]
本地部署的话只需要先
`python3 setup.py install`安装依赖，然后
开机的时候自动运行`python3 manage.py runserver`启动服务即可。其他设置可以参考[这里](https://github.com/the0demiurge/ShadowSocksShare-OpenShift#heroku-%E9%83%A8%E7%BD%B2%E6%96%B9%E6%B3%95)第五条：）
