### ISSUE TITLE
heroku部署站点无法被搜索引擎搜索到

### ISSUE THREAD

**Issue by loremwalker** [the0demiurge/ShadowSocksShare-OpenShift#39]
如图
![无法搜索到](https://s1.ax2x.com/2018/04/13/NE7Lp.png)

**Comment by the0demiurge** [comment]
刚部署没几天就要求被检索，太急于求成了吧😂

**Comment by loremwalker** [comment]
这平台网站部署，还以为heroku会帮我把seo也做了，最后还是要自己动手将网站放置Google console收录，不然没法搜索到；
> 1.Keywords(关键字) 
说明：keywords用来告诉搜索引擎你网页的关键字是什么。 
举例：<META NAME ="keywords" CONTENT="life, universe, mankind, plants, 
relationships, the meaning of life, science"> 
2.description(简介) 
说明：description用来告诉搜索引擎你的网站主要内容。 
举例：`<META NAME="description" CONTENT="This page is about the meaning of 
life, the universe, mankind and plants."> `
3.robots(机器人向导) 
说明：robots用来告诉搜索机器人哪些页面需要索引，哪些页面不需要索引。 
CONTENT的参数有all,none,index,noindex,follow,nofollow。默认是all。 
举例：`<META NAME="robots" CONTENT="none"> `
4.author(作者) 
说明：标注网页的作者 
举例：`<META name="AUTHOR" content="ajie,ajie@netease.com"> `
[转载自该站点](http://www.bkjia.com/HTML5/1127577.html)
