### ISSUE TITLE
生成的订阅内有很多重复的服务器配置，希望能作一下去重

### ISSUE THREAD

**Issue by Justsoos** [the0demiurge/ShadowSocksShare-OpenShift#4]
如题
比如 http://ss.pythonic.life/subscribe 重复ssr服务器配置很多

**Comment by the0demiurge** [comment]
虽然看起来是一样的，但是并不是从同一个页面爬下来的，所以实际上信息并不相同，只是名字相同而已

不信的话可以直接点开网页上的详细信息，对比一下：）

比起这个，里面有好多用不了的账号需要剔除，不过我暂时没有想到怎么验证账号可用性，因为ssr的Python 客户端需要root 权限，而openshift 不给权限。

**Comment by Justsoos** [comment]
你提到的账号是否有效的确很有必要做，但确实不好做。

还有另外一种重复，下面两个是从最近的 feed  http://ss.pythonic.life/subscribe 里提取到的，除了备注不同，其他完全相同

ssr://MTAzLjg1LjE4Ny4xMTo4OTY0OmF1dGhfY2hhaW5fYTpub25lOnRsczEuMl90aWNrZXRfYXV0aDpRWFJoY21GemFHbHBVMlZyWVdrLz9vYmZzcGFyYW09JnJlbWFya3M9VTJoaFpHOTNjMjlqYTNQbGhZM290TG5vdEtibGo3ZmxpSWJrdXFzZ2ZDRHBnSmZtcjVUbW9Mbm1qYTdsbkxBZ05TQlRVMUkmZ3JvdXA9UTJoaGNteGxjeUJZZFE

ssr://MTAzLjg1LjE4Ny4xMTo4OTY0OmF1dGhfY2hhaW5fYTpub25lOnRsczEuMl90aWNrZXRfYXV0aDpRWFJoY21GemFHbHBVMlZyWVdrLz9vYmZzcGFyYW09JnJlbWFya3M9YzJoaFpHOTNjMjlqYTNQa3Y3SGt1WkRwZzZnZ0xTQkhiMjluYkdVcklEQWdVMU5TJmdyb3VwPVEyaGhjbXhsY3lCWWRR

应该是同一个信息在多个网站发出造成的

**Comment by the0demiurge** [comment]
是的，这种去重没有做，不过考虑到这种情况出现得并不多，而且和失效的账号相比数量又太少，故改进去重不在日程上：）

**Comment by Justsoos** [comment]
我作了去重工具，在这里：
https://github.com/Justsoos/ss-ssr-gadget

**Comment by Justsoos** [comment]
批量测试，剔除工具也容易作，直接多线程 ss-local 。然后找google.com 作目标服务器。

我其实也作了，但觉得不好放上来，会引发很多社会事故，自用自用。
