### ISSUE TITLE
如何修改下链接订阅源导入的文字

### ISSUE THREAD

**Issue by loremwalker** [the0demiurge/ShadowSocksShare-OpenShift#41]
想修改一下一导入订阅源的网址就显示的名称，“Charles Xu”这样改成其他的名称像坚果面馆这样，不知道是那个源码配置文件；随便再问个问题，close的issue是不是没有通知提示了？因为仓库一直无人问津，所以这方面不是很清楚。
![rss](https://s1.ax2x.com/2018/04/25/8JGwr.png)

**Comment by wevsmy** [comment]
解析SSR,修改里面的group字段部分即可
