### ISSUE TITLE
分享一个免费的ss分享网站

### ISSUE THREAD

**Issue by JasonBai007** [the0demiurge/ShadowSocksShare-OpenShift#46]
[https://my.ishadowx.net/](https://my.ishadowx.net/)

免费，大部分情况下都能用

**Comment by the0demiurge** [comment]
我已经爬了这个网址了，只是不知道为什么只能在我自己的电脑上爬成功，服务器上爬不到

**Comment by JasonBai007** [comment]
呀，作者回复我了，受宠若惊。这个域名在我住的地方被墙了，每次访问都403，是被封了吗？以前可以上

**Comment by the0demiurge** [comment]
对，这种网站被墙并不奇怪

**Comment by JasonBai007** [comment]
现在这个项目的官网也上不去了。。。。。哎

**Comment by bygreencn** [comment]
有你们在，不封就乖乖了

**Comment by JasonBai007** [comment]
爬一下上面的网站吧，我打不开这网站，如果能从你的项目里获取到上面的ssr链接，那就好了。你解决一下在服务器上爬不到的问题呗，大神。

**Comment by the0demiurge** [comment]
这个网站封了一些ip，导致爬不了，这不是技术能解决的问题

**Comment by JasonBai007** [comment]
好吧，我刚用了两个半小时，从零开始，写了一个项目，专门爬取这个网站。项目地址：

https://github.com/JasonBai007/node-spider
