### ISSUE TITLE
非常好的项目，感谢你的无私奉献

### ISSUE THREAD

**Issue by zerowinning** [the0demiurge/ShadowSocksShare-OpenShift#8]
首先，感谢；
其次，叉一下，防止被封；
再次，感谢！

**Comment by the0demiurge** [comment]
谢谢支持：）
这也是我上谷歌学术很困难的无奈之举，能帮到大家更好地学习和科研我感到十分荣幸
![image](https://user-images.githubusercontent.com/11363529/31697256-fd32a4c8-b3e8-11e7-80bb-526d281ed910.png)
