### ISSUE TITLE
运行 python manage.py runserver 时报段错误

### ISSUE THREAD

**Issue by C-starm** [the0demiurge/ShadowSocksShare-OpenShift#84]
如题
<img width="784" alt="image" src="https://user-images.githubusercontent.com/17534292/67562007-8443f000-f750-11e9-8171-aec32ca07ddd.png">

运行环境：
RaspberryPi 3B+
raspbian 2019-09-26
python 2.7.13

**Comment by the0demiurge** [comment]
里面有个libsodium.so是x64架构的库，可能是加载的时候出的问题，你把相关的二进制库自己手动编译一下再试试吧

**Comment by C-starm** [comment]
确认了，是我自己环境的问题，我重新安装了一次系统，直接用requirements.txt安装库，就好了，非常感谢！ ORZ~
