### ISSUE TITLE
对于封锁的解决建议

### ISSUE THREAD

**Issue by awerty-noob** [the0demiurge/ShadowSocksShare-OpenShift#88]
只是个想法：
把原订阅地址内的内容定期更新在github的raw上(github本身不会被封锁)
不知道作者是否有兴趣做:)

**Comment by the0demiurge** [comment]
本项目基于最小依赖原则，希望使用最简单的部署方法，如果结合了github会增加部署复杂度

**Comment by startnoob** [comment]
定时git push
