### ISSUE TITLE
ModuleNotFoundError: No module named 'flask_script' 模块引入异常

### ISSUE THREAD

**Issue by yelexin** [the0demiurge/ShadowSocksShare-OpenShift#9]
已经 pip install -r requirments.txt 了，仍然不能运行 python manage.py runserver

**Comment by zasl** [comment]
请问你是如何安装的？我安装的都提示Could not open requirements file: [Errno 2] No such file or directory: 'distribute'
win10下 python3.5.2

**Comment by the0demiurge** [comment]
现在我的项目加入了一些ssr账号验证的功能，不再支持Windows，而且（似乎）也不再支持前置代理，以后需要部署建议部署在国外的服务器（比如heroku）里面
